// ── miz.ts — generate a valid DCS World .miz (a ZIP) from balanced keysites ──────
//
// Output pipeline tail:  balanced Keysite[]  →  projected DcsZone[]  →  mission
// table  →  serialized Lua  →  zipped .miz.  The .miz is an EMPTY Caucasus (or other
// theatre) mission carrying author-placed trigger zones — one circle per keysite.
// The EECH campaign port (Scripts/ee-dcs/zones.lua) reads these zones at
// runtime: a zone's COLOUR sets the side (blue={0,0,1}/red={1,0,0}) and the first word
// of its NAME sets the keysite type (airbase/farp/factory/…).
//
// By default the generator also SHIPS THE CAMPAIGN LUA inside the .miz so the file is
// directly playable: the built bundle (dist/ee-dcs.lua, mirrored into
// src/generated by scripts/sync-campaign.mjs) is embedded as l10n/DEFAULT/<name> and
// wired to run at mission start via mission.initScriptFile → a mapResource ResKey — the
// exact mechanism the DCS Mission Editor's "DO SCRIPT FILE" mission-init writes. Pass
// { bakeCampaign: false } to emit a zones-only .miz the author scripts themselves.
//
// The mission-table shape, key set, and the exact trigger-zone layout mirror what the
// DCS Mission Editor writes (studied from a real extracted .miz template); DCS is
// tolerant of whitespace, so the serializer matches structure/quoting, not byte layout.

import type { Keysite, DcsZone, Terrain, Side } from './types';
import { latLonToDcs } from './projection';
import type { UnitTypes } from './units';
import { unitConfigLua } from './units';
import { buildClientSlots } from './slots';
import { controlMeasureGeoJsonFeatures } from './control_measures';
import type { ScenarioControlMeasures } from './control_measures';

// The built EECH campaign bundle (~1 MB) is mirrored from the repo-root build output by
// scripts/sync-campaign.mjs (npm pre{dev,build,check} hooks) — rebuild the campaign and
// the freshest bytes ship with every generated .miz. It's loaded lazily inside buildMiz
// (a `?raw` dynamic import) so it lands in its own chunk and never weighs down first paint.
async function loadCampaignBundle(): Promise<string> {
  const mod = await import('../generated/campaign-bundle.lua?raw');
  return mod.default;
}

// Filename the campaign bundle takes inside the .miz, and the mapResource key that
// points mission-init at it. Names match the hand-authored template so DCS loads it
// as the mission initialization script exactly as the Mission Editor would.
const CAMPAIGN_LUA_NAME = 'ee-dcs.lua';
const INIT_SCRIPT_RESKEY = 'ResKey_initScript_10';

// Coalition/country roster. Both runtime spawns and baked Client slots use the
// Combined Joint Task Force countries. DCS derives physical coalition from the
// country roster, so these IDs must be declared on their matching mission side.
const CJTF_BLUE_ID = 80;
const CJTF_RED_ID = 81;
const NEUTRAL_COUNTRY_IDS: number[] = [];
for (let id = 0; id <= 92; id++) {
  if (id !== 14 && id !== CJTF_BLUE_ID && id !== CJTF_RED_ID) {
    NEUTRAL_COUNTRY_IDS.push(id);
  }
}

// ── Lua table serializer (DCS Mission Editor style) ─────────────────────────────
//
// Emits tab-indented `["key"] = value,` / `[n] = value,` lines exactly the way DCS
// writes mission files. Only needs to serialize the plain JSON-like tables we build
// below (numbers, strings, booleans, nested objects, and arrays).

export type LuaValue = number | string | boolean | LuaTable;
export interface LuaObject {
  [key: string]: LuaValue;
}
export type LuaTable = LuaObject | LuaValue[];

const TAB = '\t';

function indent(level: number): string {
  return TAB.repeat(level);
}

function luaString(s: string): string {
  // Escape backslashes and double quotes; DCS mission strings are double-quoted.
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function luaNumber(n: number): string {
  if (!Number.isFinite(n)) {
    throw new Error(`miz: refusing to serialize non-finite number (${n})`);
  }
  // Integers print without a decimal point; other values keep full JS precision.
  // Our coordinate/radius ranges never reach exponent notation.
  return String(n);
}

function isTable(v: LuaValue): v is LuaTable {
  return typeof v === 'object' && v !== null;
}

function isEmptyTable(v: LuaTable): boolean {
  return Array.isArray(v) ? v.length === 0 : Object.keys(v).length === 0;
}

/** Serialize a scalar or a table. Tables begin with `{` at column `level`. */
function serializeValue(v: LuaValue, level: number): string {
  switch (typeof v) {
    case 'number':
      return luaNumber(v);
    case 'string':
      return luaString(v);
    case 'boolean':
      return v ? 'true' : 'false';
    default:
      return serializeTable(v as LuaTable, level);
  }
}

function serializeTable(tbl: LuaTable, level: number): string {
  if (isEmptyTable(tbl)) return '{}';

  const pad = indent(level);
  const padIn = indent(level + 1);
  const entries: Array<[string, LuaValue]> = Array.isArray(tbl)
    ? tbl.map((val, i): [string, LuaValue] => [`[${i + 1}]`, val])
    : Object.entries(tbl);

  let out = '{\n';
  for (const [rawKey, val] of entries) {
    const key = rawKey.startsWith('[') ? rawKey : `[${luaString(rawKey)}]`;
    if (isTable(val) && !isEmptyTable(val)) {
      // Nested non-empty table: key on its own line, `{` on the next (DCS style).
      out += `${padIn}${key} = \n${padIn}${serializeValue(val, level + 1)},\n`;
    } else {
      out += `${padIn}${key} = ${serializeValue(val, level + 1)},\n`;
    }
  }
  out += `${pad}}`;
  return out;
}

/** Serialize a named top-level table, e.g. `mission = { … }`, as a .miz entry body. */
export function serializeNamed(name: string, tbl: LuaTable): string {
  return `${name} = \n${serializeTable(tbl, 0)} -- end of ${name}\n`;
}

// ── Keysites → trigger zones ─────────────────────────────────────────────────────

// DCS Mission Editor default trigger-zone fill alpha (38/255). Only R and B are read
// by the port (zones.lua side_of_color); alpha is cosmetic but kept ME-faithful.
const ZONE_ALPHA = 0.14901960784314;
// Zone ids must be unique within the mission; ME assigns small integers. Start high
// enough to avoid colliding with anything an author might later add by hand.
const ZONE_ID_BASE = 100;

function zoneColor(side: Side): [number, number, number, number] {
  return side === 'blue' ? [0, 0, 1, ZONE_ALPHA] : [1, 0, 0, ZONE_ALPHA];
}

/** Keep zone names to a safe charset while preserving the leading type word so
 *  zones.lua's `^%s*(%a+)` type selector still resolves to the keysite type. */
function sanitizeLabel(label: string): string {
  const cleaned = label
    .trim()
    .replace(/[^A-Za-z0-9]+/g, '-') // collapse runs of unsafe chars to a dash
    .replace(/^-+|-+$/g, ''); // trim leading/trailing dashes
  return cleaned.length > 0 ? cleaned : 'site';
}

/**
 * Project each keysite to DCS coordinates and turn it into a circular trigger zone.
 * name = `${type}_${label}` — the bare type is the first %a+ run so the port classifies
 * it; colour encodes the side. x = DCS north, y = DCS east (matching zones.lua's mapping).
 */
export function keysitesToZones(keysites: Keysite[], terrain: Terrain): DcsZone[] {
  return keysites.map((ks, i): DcsZone => {
    const dcs = latLonToDcs(ks.latlon, terrain);
    if (!Number.isFinite(dcs.x) || !Number.isFinite(dcs.y)) {
      throw new Error(
        `miz: keysite "${ks.label}" projected to a non-finite DCS point ` +
          `(${dcs.x}, ${dcs.y}); check the keysite's lat/lon and the terrain projection`,
      );
    }
    return {
      zoneId: ZONE_ID_BASE + i,
      name: `${ks.type}_${sanitizeLabel(ks.label)}`,
      x: dcs.x,
      y: dcs.y,
      radius: ks.radiusM,
      color: zoneColor(ks.side),
      side: ks.side,
      type: ks.type,
    };
  });
}

/** One DcsZone → the Lua sub-table DCS writes under triggers.zones (type 0 = circle). */
function zoneToLua(z: DcsZone): LuaObject {
  return {
    radius: z.radius,
    zoneId: z.zoneId,
    color: [z.color[0], z.color[1], z.color[2], z.color[3]],
    properties: {},
    hidden: false,
    y: z.y,
    x: z.x,
    name: z.name,
    heading: 0,
    type: 0, // 0 = circle (2 would be a quad); NOT the keysite type.
  };
}

// ── Minimal, valid mission skeleton ──────────────────────────────────────────────

function coalitionCountry(id: number, name: string): LuaObject {
  return { id, name };
}

function emptyCoalitionSide(name: string, countries: LuaObject[] = []): LuaObject {
  return {
    bullseye: { y: 0, x: 0 },
    nav_points: {},
    name,
    // No campaign units are pre-placed (spawned at runtime), but baked human-flyable
    country: countries,
  };
}

const COUNTRY_BY_SIDE: Record<Side, { id: number; name: string }> = {
  blue: { id: CJTF_BLUE_ID, name: 'CJTF Blue' },
  red: { id: CJTF_RED_ID, name: 'CJTF Red' },
};

interface FarpResult {
  groups: Record<Side, LuaValue[]>;
  warehouses: LuaObject;
}

function highestId(value: LuaValue | undefined, key: 'groupId' | 'unitId'): number {
  if (value === undefined || typeof value !== 'object' || value === null) return 0;
  if (Array.isArray(value)) return Math.max(0, ...value.map((entry) => highestId(entry, key)));
  const direct = typeof value[key] === 'number' ? value[key] as number : 0;
  return Math.max(direct, ...Object.values(value).map((entry) => highestId(entry, key)));
}

function unlimitedFarpWarehouse(side: Side): LuaObject {
  return {
    gasoline: { InitFuel: 100 },
    unlimitedMunitions: true,
    methanol_mixture: { InitFuel: 100 },
    OperatingLevel_Air: 10,
    diesel: { InitFuel: 100 },
    speed: 16.666666,
    dynamicSpawn: false,
    unlimitedAircrafts: true,
    periodicity: 30,
    jet_fuel: { InitFuel: 100 },
    size: 100,
    suppliers: {},
    coalition: side,
    dynamicCargo: true,
    OperatingLevel_Eqp: 10,
    allowHotStart: false,
    aircrafts: {},
    weapons: {},
    OperatingLevel_Fuel: 10,
    unlimitedFuel: true,
  };
}

function buildFarps(zones: DcsZone[], slots?: { blue: LuaObject | null; red: LuaObject | null }): FarpResult {
  const groups: Record<Side, LuaValue[]> = { blue: [], red: [] };
  const warehouses: LuaObject = {};
  let groupId = Math.max(
    highestId(slots?.blue ?? undefined, 'groupId'),
    highestId(slots?.red ?? undefined, 'groupId'),
  ) + 1;
  let unitId = Math.max(
    highestId(slots?.blue ?? undefined, 'unitId'),
    highestId(slots?.red ?? undefined, 'unitId'),
  ) + 1;

  for (const zone of zones) {
    if (zone.type !== 'farp') continue;
    // zones.keysites() retains the whole trigger-zone name as label. The campaign's
    // Airbase lookup therefore requires this exact static unit name.
    const logicalName = `FARP-${zone.name}`;
    const staticGroupName = `Static ${logicalName}`;
    const thisGroupId = groupId++;
    const thisUnitId = unitId++;
    groups[zone.side].push({
      heading: 0,
      route: {
        points: [{
          alt: 0,
          type: '',
          name: '',
          y: zone.y,
          speed: 0,
          x: zone.x,
          formation_template: '',
          action: '',
        }],
      },
      groupId: thisGroupId,
      units: [{
        tasks: {},
        category: 'Heliports',
        shape_name: 'FARPS',
        type: 'FARP',
        unitId: thisUnitId,
        heliport_frequency: '127.5',
        y: zone.y,
        x: zone.x,
        name: logicalName,
        heliport_modulation: 0,
        heliport_callsign_id: 1,
        heading: 0,
      }],
      y: zone.y,
      x: zone.x,
      name: staticGroupName,
      dead: false,
    });
    warehouses[`[${thisUnitId}]`] = unlimitedFarpWarehouse(zone.side);
  }
  return { groups, warehouses };
}

function countryWithFarps(
  side: Side,
  slots: LuaObject | null | undefined,
  groups: LuaValue[],
): LuaObject {
  const country = {
    ...(slots ?? coalitionCountry(COUNTRY_BY_SIDE[side].id, COUNTRY_BY_SIDE[side].name)),
  };
  if (groups.length > 0) country.static = { group: groups };
  return country;
}

/**
 * Build a minimal but valid DCS mission table for an otherwise-empty theatre carrying
 * only the given trigger zones. Mirrors the key set the Mission Editor requires: a
 * fresh date, default clean-sky weather, empty coalitions/trig/result, and the zones.
 * Descriptions are plain empty strings (not DictKey refs) so a `dictionary = {}` and
 * `mapResource` companion suffice and there are no dangling references.
 *
 * `initScriptFile` is the mapResource ResKey of the mission-init script to run at start
 * (empty string = none). When set, a matching mapResource entry + embedded l10n file
 * must accompany it (buildMiz wires all three together).
 */
export function buildMissionTable(
  zones: DcsZone[],
  terrain: Terrain,
  initScriptFile = '',
  slots?: { blue: LuaObject | null; red: LuaObject | null },
  farps: FarpResult = buildFarps(zones, slots),
): LuaObject {
  const zoneTables: LuaValue[] = zones.map(zoneToLua);

  // Frame the ME map view on the centroid of the zones (or origin if none).
  let centerX = 0;
  let centerY = 0;
  if (zones.length > 0) {
    for (const z of zones) {
      centerX += z.x;
      centerY += z.y;
    }
    centerX /= zones.length;
    centerY /= zones.length;
  }

  return {
    // ResKey of the mission-init script (see buildMiz). Empty = zones-only mission.
    initScriptFile,
    groundControl: {
      passwords: {
        artillery_commander: {},
        instructor: {},
        observer: {},
        forward_observer: {},
      },
      roles: {
        artillery_commander: { neutrals: 0, blue: 0, red: 0 },
        instructor: { neutrals: 1, blue: 1, red: 1 },
        observer: { neutrals: 0, blue: 0, red: 0 },
        forward_observer: { neutrals: 0, blue: 0, red: 0 },
      },
      isPilotControlVehicles: true,
    },
    requiredModules: {},
    date: { Year: 2016, Day: 21, Month: 6 },
    trig: {
      actions: {},
      events: {},
      custom: {},
      func: {},
      flag: {},
      conditions: {},
      customStartup: {},
    },
    maxDictId: 0,
    result: {
      offline: { conditions: {}, actions: {}, func: {} },
      total: 0,
      blue: { conditions: {}, actions: {}, func: {} },
      red: { conditions: {}, actions: {}, func: {} },
    },
    pictureFileNameN: {},
    descriptionNeutralsTask: '',
    pictureFileNameServer: {},
    weather: {
      wind: {
        at8000: { speed: 0, dir: 0 },
        atGround: { speed: 0, dir: 0 },
        at2000: { speed: 0, dir: 0 },
      },
      enable_fog: false,
      season: { temperature: 20 },
      qnh: 760,
      cyclones: {},
      dust_density: 0,
      enable_dust: false,
      clouds: { thickness: 200, density: 0, preset: 'Preset2', base: 2500, iprecptns: 0 },
      atmosphere_type: 0,
      groundTurbulence: 0,
      halo: { preset: 'auto' },
      type_weather: 0,
      modifiedTime: false,
      name: 'Winter, clean sky',
      fog: { visibility: 0, thickness: 0 },
      visibility: { distance: 80000 },
    },
    theatre: terrain.id,
    triggers: { zones: zoneTables },
    map: { centerY, zoom: 100, centerX },
    coalitions: {
      blue: [CJTF_BLUE_ID],
      neutrals: NEUTRAL_COUNTRY_IDS,
      red: [CJTF_RED_ID],
    },
    descriptionText: '',
    pictureFileNameR: {},
    descriptionBlueTask: '',
    goals: {},
    descriptionRedTask: '',
    pictureFileNameB: {},
    coalition: {
      blue: emptyCoalitionSide('blue', [
        countryWithFarps('blue', slots?.blue, farps.groups.blue),
      ]),
      neutrals: emptyCoalitionSide('neutrals'),
      red: emptyCoalitionSide('red', [
        countryWithFarps('red', slots?.red, farps.groups.red),
      ]),
    },
    sortie: '',
    version: 23,
    trigrules: {},
    currentKey: 0,
    failures: {},
    forcedOptions: {},
    start_time: 28800,
  };
}

// ── Companion .miz entries ───────────────────────────────────────────────────────

// `options` is per-user client settings; DCS reads it but it does not affect whether a
// mission opens. Embedded verbatim from the template so the .miz round-trips through ME.
const OPTIONS_LUA = `options =
{
	["playerName"] = "New callsign",
	["miscellaneous"] =
	{
		["chat_window_at_start"] = true,
		["TrackIR_external_views"] = true,
		["f11_free_camera"] = true,
		["force_feedback_enabled_custom_stick"] = false,
		["f10_awacs"] = true,
		["Coordinate_Display"] = "Precise Lat Long",
		["accidental_failures"] = false,
		["autologin"] = true,
		["show_pilot_body"] = false,
		["collect_stat"] = true,
		["synchronize_controls"] = false,
		["backup"] = false,
		["force_feedback_enabled_custom_pedals"] = false,
		["headmove"] = false,
		["f5_nearest_ac"] = true,
		["F2_view_effects"] = 1,
		["launcher"] = true,
		["backupTime"] = 5,
		["allow_server_screenshots"] = false,
		["mgrs_grid_visible"] = false,
		["collect_stat_defined"] = false,
		["geo_grid_visible"] = true,
		["force_feedback_enabled"] = true,
	}, -- end of ["miscellaneous"]
	["difficulty"] =
	{
		["fuel"] = false,
		["spottingDot"] = 3,
		["miniHUD"] = false,
		["optionsView"] = "optview_all",
		["setGlobal"] = true,
		["avionicsLanguage"] = "native",
		["cockpitVisualRM"] = false,
		["map"] = true,
		["gWarmUp"] = false,
		["spectatorExternalViews"] = true,
		["userSnapView"] = true,
		["iconsTheme"] = "nato",
		["weapons"] = false,
		["padlock"] = true,
		["birds"] = 0,
		["permitCrash"] = true,
		["immortal"] = false,
		["easyCommunication"] = true,
		["wakeTurbulence"] = false,
		["easyFlight"] = false,
		["hideStick"] = false,
		["radio"] = false,
		["geffect"] = "realistic",
		["unrestrictedSATNAV"] = false,
		["reports"] = true,
		["tips"] = true,
		["cockpitStatusBarAllowed"] = false,
		["autoTrimmer"] = false,
		["externalViews"] = true,
		["RBDAI"] = true,
		["controlsIndicator"] = true,
		["units"] = "imperial",
		["userMarks"] = true,
		["labels"] = 1,
	}, -- end of ["difficulty"]
	["VR"] =
	{
		["handOffsetZ"] = 0,
		["enableHMDMask"] = true,
		["box_mouse_cursor"] = true,
		["handOffsetY"] = 0,
		["mirror_crop"] = false,
		["pointer_use_type"] = 0,
		["mirror_use_DCS_resolution"] = false,
		["openxr_eyeGaze"] = false,
		["hand_controllers_use_throttle"] = true,
		["hand_controllers_joint_throttle"] = true,
		["use_mouse"] = true,
		["openxr_quadView"] = false,
		["custom_IPD_enable"] = false,
		["hand_controllers_type"] = 0,
		["hand_controllers_debug_draw"] = true,
		["handOffsetX"] = 0,
		["prefer_built_in_audio"] = true,
		["pixel_density"] = 1,
		["hand_controllers_use_stick"] = true,
		["msaaMaskSize"] = 0.42,
		["enable"] = false,
		["interaction_with_grip_only"] = false,
		["bloom"] = true,
		["mirror_source"] = 0,
		["custom_IPD"] = 63.5,
		["hand_controllers"] = true,
	}, -- end of ["VR"]
	["graphics"] =
	{
		["volumetricLights"] = 1,
		["AA"] = "OFF",
		["forestDetailsFactor"] = 1,
		["rainDroplets"] = 0,
		["LensEffects"] = 0,
		["heatBlr"] = 0,
		["anisotropy"] = 0,
		["water"] = 0,
		["motionBlurAmount"] = 1,
		["scaleGui"] = 1.25,
		["visibRange"] = "Low",
		["aspect"] = 1.3333333333333,
		["lights"] = 2,
		["shadows"] = 1,
		["MSAA"] = 1,
		["canopyReflections"] = 1,
		["clutterMaxDistance"] = 0,
		["textures"] = 0,
		["DLSS_PerfQuality"] = 1,
		["outputGamma"] = 2.2,
		["forestDistanceFactor"] = 0.3,
		["BlurFlatShadows"] = 0,
		["cockpitGI"] = 0,
		["terrainTextures"] = "min",
		["box_mouse_cursor"] = false,
		["multiMonitorSetup"] = "1camera",
		["messagesFontScale"] = 1,
		["defaultFOV"] = 78,
		["shadowTree"] = false,
		["chimneySmokeDensity"] = 1,
		["maxFPS"] = 300,
		["SSS"] = 0,
		["fullScreen"] = false,
		["useDeferredShading"] = 1,
		["effects"] = 3,
		["Scaling"] = 0.66,
		["DOF"] = 0,
		["clouds"] = 0,
		["sceneryDetailsFactor"] = 1,
		["Upscaling"] = "OFF",
		["flatTerrainShadows"] = 1,
		["LODmult"] = 1,
		["secondaryShadows"] = 1,
		["ColorGradingLUT"] = 0,
		["SSLR"] = 0,
		["width"] = 1920,
		["SSAO"] = 0,
		["Sharpening"] = 1,
		["sync"] = false,
		["preloadRadius"] = 100,
		["height"] = 1440,
		["motionBlur"] = 0,
		["ScreenshotExt"] = "jpg",
		["civTraffic"] = "",
	}, -- end of ["graphics"]
	["plugins"] = {},
	["format"] = 1,
	["sound"] =
	{
		["main_output"] = "",
		["FakeAfterburner"] = false,
		["volume"] = 80,
		["headphones_on_external_views"] = true,
		["subtitles"] = true,
		["voiceChatInVolume"] = 50,
		["world"] = 100,
		["hear_in_helmet"] = false,
		["hp_output"] = "",
		["music"] = 60,
		["main_layout"] = "",
		["headphones"] = 100,
		["cockpit"] = 100,
		["voice_chat_output"] = "",
		["voice_chat"] = true,
		["GBreathEffect"] = true,
		["radioSpeech"] = true,
		["switches"] = 100,
		["play_audio_while_minimized"] = false,
		["voiceChatInSensitivity"] = -50,
		["microphone_use"] = 2,
		["voice_chat_input"] = "",
		["gui"] = 100,
	}, -- end of ["sound"]
	["views"] =
	{
		["cockpit"] =
		{
			["reflections"] = false,
			["mirrorsSequentialRendering"] = true,
			["avionicsMFDEveryFrame"] = false,
			["mirrors"] = false,
			["mirrorsEveryFrame"] = false,
			["mirrorsResolution"] = 1,
			["avionics"] = 0,
		}, -- end of ["cockpit"]
	}, -- end of ["views"]
} -- end of options
`;

function warehousesLua(farps: FarpResult): string {
  return serializeNamed('warehouses', { warehouses: farps.warehouses, airports: {} });
}

/** Empty localization dictionary — the mission carries no DictKey references. */
const DICTIONARY_LUA = 'dictionary = \n{\n} -- end of dictionary\n';

/** Empty map-resource table — used when no campaign script is baked in. */
const MAP_RESOURCE_EMPTY = 'mapResource = \n{\n} -- end of mapResource\n';

/** mapResource pointing the mission-init ResKey at the embedded campaign bundle. */
const MAP_RESOURCE_WITH_INIT = serializeNamed('mapResource', {
  [INIT_SCRIPT_RESKEY]: CAMPAIGN_LUA_NAME,
});

// ── Public entry: assemble the .miz ──────────────────────────────────────────────

/** Options controlling .miz assembly. */
export interface BuildMizOptions {
  /** Embed the EECH campaign bundle + wire it to run at mission start. Default true —
   *  the output is a directly-playable campaign. Set false for a zones-only .miz. */
  bakeCampaign?: boolean;
  /** Per-side aircraft type overrides. When any differ from the port defaults, a
   *  `_G.DMT_CONFIG` snippet is prepended to the baked bundle. Also drives which aircraft
   *  types get baked Client slots. */
  unitTypes?: UnitTypes;
  /** Bake 4 human-flyable Client slots per aircraft type at each compatible airbase
   *  (needs terrain parking data — see slots.ts). Default true. */
  bakeSlots?: boolean;
  /** Operational framework retained in the archive for campaign coordination tooling. */
  controlMeasures?: ScenarioControlMeasures;
}

/** Deterministic .miz filename for a terrain, e.g. `eech-caucasus.miz`. */
export function filenameFor(terrain: Terrain): string {
  return `eech-${terrain.id.toLowerCase()}.miz`;
}

/**
 * Build a complete, ME-openable .miz (ZIP) for the given keysites and terrain. The
 * archive holds the entries a real .miz needs: `mission`, `options`, `warehouses`,
 * `theatre`, and the DEFAULT localization pair. When `bakeCampaign` is true (default)
 * the campaign bundle is embedded as `l10n/DEFAULT/ee-dcs.lua` and wired
 * to run at mission start, so the file plays the EECH campaign with no further setup.
 * Returns a Blob.
 */
export async function buildMiz(
  keysites: Keysite[],
  terrain: Terrain,
  opts: BuildMizOptions = {},
): Promise<Blob> {
  const bakeCampaign = opts.bakeCampaign ?? true;
  const bakeSlots = opts.bakeSlots ?? true;
  const { default: JSZip } = await import('jszip');

  const zones = keysitesToZones(keysites, terrain);
  const initScriptFile = bakeCampaign ? INIT_SCRIPT_RESKEY : '';
  const slots = bakeSlots ? buildClientSlots(keysites, terrain, opts.unitTypes) : undefined;
  if (slots) {
    console.info(`miz: baked ${slots.slotCount} Client slot(s)`);
    if (slots.notes.length) console.info('miz slot notes:\n  ' + slots.notes.join('\n  '));
  }
  const farps = buildFarps(zones, slots);
  const mission = buildMissionTable(zones, terrain, initScriptFile, slots, farps);
  const missionLua = serializeNamed('mission', mission);

  const zip = new JSZip();
  zip.file('mission', missionLua);
  zip.file('options', OPTIONS_LUA);
  zip.file('warehouses', warehousesLua(farps));
  zip.file('theatre', terrain.id);
  zip.file('l10n/DEFAULT/dictionary', DICTIONARY_LUA);
  zip.file('l10n/DEFAULT/mapResource', bakeCampaign ? MAP_RESOURCE_WITH_INIT : MAP_RESOURCE_EMPTY);
  if (opts.controlMeasures) {
    zip.file(
      'control-measures.geojson',
      JSON.stringify({
        type: 'FeatureCollection',
        properties: { terrain: terrain.id },
        features: controlMeasureGeoJsonFeatures(opts.controlMeasures),
      }, null, 2),
    );
  }
  if (bakeCampaign) {
    // Prepend any aircraft-type overrides so config.lua reads _G.DMT_CONFIG at load,
    // then the campaign bundle itself.
    const cfg = opts.unitTypes ? unitConfigLua(opts.unitTypes) : '';
    zip.file(`l10n/DEFAULT/${CAMPAIGN_LUA_NAME}`, cfg + (await loadCampaignBundle()));
  }

  return zip.generateAsync({
    type: 'blob',
    mimeType: 'application/octet-stream',
    compression: 'DEFLATE',
  });
}
