// ── Precompiled OSM data source ─────────────────────────────────────────────────
// Theatre datasets are generated by scripts/export-osm.mjs and served as static gzip assets.
// Plain static hosts may not set Content-Encoding, so use native stream decompression there.

import { KEYSITE_TYPES } from './types';
import type { OsmFeature } from './types';

export async function loadTheatreOsm(
  theatreId: string,
): Promise<{ features: OsmFeature[] }> {
  const url = `${import.meta.env.BASE_URL}osm/${encodeURIComponent(theatreId)}.geojson.gz`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Could not load the OSM export for ${theatreId}: HTTP ${response.status}`);
  const httpDecoded = response.headers.get('content-encoding')?.toLowerCase().split(',').some((value) => value.trim() === 'gzip');
  let raw: string;
  if (httpDecoded) {
    raw = await response.text();
  } else {
    if (!response.body) throw new Error(`The OSM export for ${theatreId} has no response body`);
    if (typeof DecompressionStream === 'undefined') {
      throw new Error('This browser cannot open the compressed OSM export');
    }
    raw = await new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).text();
  }
  const data = JSON.parse(raw) as {
    type: 'FeatureCollection';
    features: Array<{
      geometry: { type: 'Point'; coordinates: [number, number] };
      properties: {
        kind?: string;
        osmId: string;
        name?: string;
        tags?: Record<string, string>;
      };
    }>;
  };
  const features: OsmFeature[] = [];
  for (const feature of data.features) {
    if (feature.geometry.type === 'Point') {
      const rawKind = feature.properties.kind;
      const kind = KEYSITE_TYPES.find((type) => type === rawKind);
      if (rawKind !== undefined && kind === undefined) {
        throw new Error(`Unknown OSM keysite kind "${rawKind}" for ${feature.properties.osmId}`);
      }
      features.push({
        id: feature.properties.osmId,
        latlon: { lat: feature.geometry.coordinates[1], lon: feature.geometry.coordinates[0] },
        tags: feature.properties.tags ?? {},
        name: feature.properties.name ?? feature.properties.tags?.['name:en'] ?? feature.properties.tags?.name,
        kind,
      });
    }
  }
  return { features };
}
